name = "comic-parser"
main = "src/index.ts"
compatibility_date = "2023-12-06"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
# [[kv_namespaces]]
binding = "COMIC_KV"
id = "af011b9fec2d47498e2f68b1ec895963"

node_compat = true

kv_namespaces = [
  { binding = "COMIC_KV", id = "af011b9fec2d47498e2f68b1ec895963" }
]
